name: Frontend CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy-front:
    runs-on: ubuntu-latest
    environment: ricofilm  # Sp√©cifiez l'environnement ici
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build --prod

      - name: Build Docker image
        run: docker build -t ghcr.io/ricohoho/frontend:latest -f Dockerfile .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ricohoho --password-stdin

      - name: Push Docker image
        run:  docker push ghcr.io/ricohoho/frontend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ricohoho --password-stdin
            docker pull ghcr.io/ricohoho/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 4200:80 ghcr.io/ricohoho/frontend:latest

